import * as cheerio from 'cheerio';
import type { Section, Paragraph } from '../types.js';
import { titleFor, titleVariantsFor } from './items.js';

/**
 * HTML → ordered lines of visible text.
 *
 * EDGAR filings are generated by a dozen different vendors; the only thing
 * they reliably share is that block-level elements delimit paragraphs.
 * We keep that structure and throw everything else away.
 */
export function htmlToLines(html: string): string[] {
  const $ = cheerio.load(html);
  $('script, style, noscript, head').remove();
  // Cells get a space so "Item 1A." + "Risk Factors" + "9" don't fuse into one token.
  $('td, th').each((_, el) => {
    $(el).append(' ');
  });
  // Force a line break after every block-level element.
  $('p, div, tr, li, h1, h2, h3, h4, h5, h6, table, section, article, blockquote, pre').each((_, el) => {
    $(el).append('\n');
  });
  $('br').replaceWith('\n');
  const raw = $('body').length ? $('body').text() : $.root().text();
  const lines = raw
    .replace(/[​﻿­]/g, '') // zero-width space / BOM / soft hyphen — everywhere in EDGAR HTML
    .replace(/ /g, ' ')
    .split('\n')
    .map((l) => l.replace(/[ \t\r\f\v]+/g, ' ').trim())
    .filter((l) => l.length > 0);
  const furnitureCounts = new Map<string, number>();
  for (const line of lines) {
    const normalised = furnitureKey(line);
    if (normalised) furnitureCounts.set(normalised, (furnitureCounts.get(normalised) ?? 0) + 1);
  }
  return lines.filter((line) => {
    const normalised = furnitureKey(line);
    return !normalised || (furnitureCounts.get(normalised) ?? 0) < 3;
  });
}

/** Short repeated lines explicitly marked as filing/page labels are page furniture. */
function furnitureKey(line: string): string | undefined {
  if (line.length >= 80 || !/\d/.test(line)) return undefined;
  if (!/form\s+10-[kq]\b|\bpage\s+\d/i.test(line)) return undefined;
  return line.replace(/\d/g, '#');
}

const PART_RE = /^part\s+(i{1,3}|iv|[1-4])\s*[.:\-–—]?\s*(.*)$/i;
const ITEM_TOKEN = '\\d{1,2}[a-c]?';
const ITEM_RANGE = `${ITEM_TOKEN}\\s*(?:through|[-–—])\\s*${ITEM_TOKEN}`;
const ITEM_LIST = `${ITEM_TOKEN}(?:\\s*,\\s*${ITEM_TOKEN})*(?:\\s*,?\\s+and\\s+${ITEM_TOKEN})?`;
// "Item 1A." / "Items 5 and 6." / "Items 10 through 14" ...
const ITEM_RE = new RegExp(`^(items?)\\s+(${ITEM_RANGE}|${ITEM_LIST})\\s*[.:\\-–—]?\\s*(.*)$`, 'i');
const MAX_HEADING_CHARS = 140;
const MAX_TITLE_WORDS = 12;
/** Bodies shorter than this are returned only with a warning; TOC stubs never are. */
export const MIN_BODY_CHARS = 400;
/** ≥ this many headings within TOC_MAX_GAP lines of each other = a table of contents. */
const TOC_MIN_RUN = 3;
const TOC_MAX_GAP = 2;
/** TOC rows have no substantive body after page-number noise is removed. */
const TOC_STUB_BODY_CHARS = 40;
// hasPageRef / classify below implement the cluster rule.

interface Heading {
  keys: string[];
  rawTitle: string;
  line: number;
  combinedLabel?: string;
  fusedParagraph?: string;
  splitTitle?: string;
}

const ROMAN: Record<string, string> = { '1': 'I', '2': 'II', '3': 'III', '4': 'IV' };

/** Lines that are page furniture rather than content. */
function isNoise(line: string): boolean {
  if (/^\d{1,3}$/.test(line)) return true; // page numbers
  if (/^table of contents$/i.test(line)) return true;
  if (/^(?:(?:fiscal\s+)?\d{4}\s+)?(?:form\s+)?10-[kq]\b/i.test(line) && line.length < 60) return true;
  const part = PART_RE.exec(line);
  if (part && line.length < 60 && !looksLikeSentence(part[2] ?? '')) return true; // "PART II. OTHER INFORMATION"
  return false;
}

/**
 * "Item 7 of our revenue was…" and "Item 1A of Part I is incorporated…" are
 * sentences, not headings. A heading's title is short and starts with a capital.
 */
function looksLikeSentence(title: string): boolean {
  const t = title.trim();
  if (!t) return false;
  if (/^[a-z]/.test(t)) return true; // "of our revenue…"
  if (t.split(/\s+/).length > MAX_TITLE_WORDS) return true;
  return false;
}

interface FusedHeading {
  rawTitle: string;
  paragraph: string;
  splitTitle: string;
}

function comparableTitle(value: string): string {
  return value.toLocaleLowerCase('en-US').replace(/[‘’]/g, "'");
}

function matchesKnownTitle(raw: string, form: string, keys: string[]): boolean {
  const key = keys.length === 1 ? keys[0] : undefined;
  if (!key) return false;
  const candidate = raw.trim().replace(/[.:\-–—]+$/, '').trim();
  return titleVariantsFor(form, key).some((variant) => comparableTitle(candidate) === comparableTitle(variant));
}

function sentenceLikeRemainder(value: string): boolean {
  return /^[A-Z]/.test(value) && value.trim().split(/\s+/).length >= 3;
}

/** Split only at a known Item title or, for long lines, an unambiguous nearby sentence boundary. */
function splitFusedHeading(raw: string, form: string, keys: string[], allowSentenceBoundary: boolean): FusedHeading | undefined {
  for (const variant of keys.length === 1 && keys[0] ? titleVariantsFor(form, keys[0]) : []) {
    const found = raw.slice(0, variant.length);
    if (comparableTitle(found) !== comparableTitle(variant)) continue;
    const rest = raw.slice(variant.length);
    const body = /^[.:–—-]?\s+(.+)$/.exec(rest)?.[1];
    if (body && sentenceLikeRemainder(body)) return { rawTitle: found, paragraph: body, splitTitle: found };
  }

  if (!allowSentenceBoundary) return undefined;
  for (let i = 0; i < Math.min(raw.length, 120); i++) {
    if (!/[.!?]/.test(raw[i] ?? '')) continue;
    const rest = raw.slice(i + 1);
    const body = /^\s+([A-Z].*)$/.exec(rest)?.[1];
    if (!body) continue;
    const headingTitle = raw.slice(0, i + 1);
    if (looksLikeSentence(headingTitle)) return undefined;
    return { rawTitle: headingTitle, paragraph: body, splitTitle: headingTitle };
  }
  return undefined;
}

function expandItemRange(spec: string): string[] | undefined {
  const match = new RegExp(`^(${ITEM_TOKEN})\\s*(?:through|[-–—])\\s*(${ITEM_TOKEN})$`, 'i').exec(spec);
  if (!match?.[1] || !match[2]) return undefined;
  const start = /^(\d{1,2})([a-c]?)$/i.exec(match[1]);
  const end = /^(\d{1,2})([a-c]?)$/i.exec(match[2]);
  if (!start?.[1] || !end?.[1] || start[2] || end[2]) return undefined;
  const first = Number(start[1]);
  const last = Number(end[1]);
  if (last < first || last - first > 20) return undefined;
  return Array.from({ length: last - first + 1 }, (_, i) => String(first + i));
}

function itemKeys(spec: string): string[] | undefined {
  const range = expandItemRange(spec);
  if (range) return range;
  const keys = spec.match(new RegExp(ITEM_TOKEN, 'gi'))?.map((key) => key.toUpperCase()) ?? [];
  return keys.length > 0 && new Set(keys).size === keys.length ? keys : undefined;
}

/** TOC rows almost always end in a page reference: "Item 1A. Risk Factors 9". */
function hasPageRef(title: string): boolean {
  const pageList = '(?:pages?\\s+)?\\d{1,4}(?:\\s*-\\s*\\d{1,4})?(?:\\s*,\\s*\\d{1,4}(?:\\s*-\\s*\\d{1,4})?)*';
  return new RegExp(`(?:^|\\s)${pageList}$`, 'i').test(title)
    || /\s(?:not applicable|none|n\/a)$/i.test(title)
    || /\s\([a-e]\)$/i.test(title);
}

interface Classified extends Heading {
  bodyChars: number;
  placeholderBody: boolean;
  /** Sits inside a table-of-contents cluster; never a section. */
  toc: boolean;
  /** Big body directly after a TOC cluster: either the first real heading or the last TOC row
   *  swallowing the preamble. Used only when no unflagged candidate exists. */
  tocTail: boolean;
}

/**
 * Classify headings. A run of ≥ TOC_MIN_RUN headings within TOC_MAX_GAP lines of
 * each other is a table of contents only when at least half of its members have
 * a page reference or an empty body. Members whose title carries a page reference,
 * or whose body is tiny, are dropped. A member with a real body and no page
 * reference ends the run and is flagged `tocTail`.
 */
function classify(headings: Heading[], bodyInfo: (i: number) => { chars: number; placeholder: boolean }): Classified[] {
  const out: Classified[] = headings.map((h, i) => {
    const body = bodyInfo(i);
    return { ...h, bodyChars: body.chars, placeholderBody: body.placeholder, toc: false, tocTail: false };
  });
  let runStart = 0;
  const closeRun = (endExclusive: number): void => {
    const runLength = endExclusive - runStart;
    if (runLength < TOC_MIN_RUN) return;
    const tocSignals = out.slice(runStart, endExclusive).filter((member) => hasPageRef(member.rawTitle) || member.bodyChars === 0).length;
    if (tocSignals * 2 < runLength) return;
    for (let k = runStart; k < endExclusive; k++) {
      const m = out[k];
      if (!m) continue;
      const stub = (!m.placeholderBody && m.bodyChars < TOC_STUB_BODY_CHARS) || hasPageRef(m.rawTitle);
      if (stub) m.toc = true;
      else m.tocTail = true; // only ever the final member — a stub would have continued the run
    }
  };
  for (let i = 1; i <= out.length; i++) {
    const prev = out[i - 1];
    const cur = out[i];
    const prevIsStub = prev !== undefined
      && ((!prev.placeholderBody && prev.bodyChars < TOC_STUB_BODY_CHARS) || hasPageRef(prev.rawTitle));
    const contiguous = cur !== undefined && prev !== undefined && cur.line - prev.line <= TOC_MAX_GAP && prevIsStub;
    if (!contiguous) {
      closeRun(i);
      runStart = i;
    }
  }
  return out;
}

/**
 * Split a filing into Items.
 *
 * Every 10-K lists all Items twice — once in the table of contents, once as
 * real headings. Two defences, in order:
 *  1. drop clusters of headings that sit within a couple of lines of each other
 *     (that is a TOC, whatever markup it uses);
 *  2. if an Item still has several occurrences, keep the one with the largest body.
 * Short real bodies ("None.", "Not applicable.") are returned with a warning.
 */
export function splitItems(lines: string[], form: string): { sections: Map<string, Section>; warnings: string[] } {
  const warnings: string[] = [];
  const all: Heading[] = [];
  let part: string | null = null;
  const isTenQ = form.startsWith('10-Q');
  let crossReferenceIndexAt = -1;
  for (let i = lines.length - 1; i >= 0; i--) {
    if (/^form\s+10-k\s+cross[- ]reference\s+index(?:\s+page\(s\))?$/i.test(lines[i] ?? '')) {
      crossReferenceIndexAt = i;
      break;
    }
  }

  lines.forEach((line, i) => {
    let headingLine = line;
    const p = PART_RE.exec(line);
    if (line.length <= MAX_HEADING_CHARS && p && p[1] && !looksLikeSentence(p[2] ?? '')) {
      const raw = p[1].toUpperCase();
      part = ROMAN[raw] ?? raw;
      headingLine = line.replace(/^part\s+(?:i{1,3}|iv|[1-4])\s*[,.:\-–—]\s*/i, '');
      if (headingLine === line) return;
    }
    if (crossReferenceIndexAt >= 0 && i > crossReferenceIndexAt) return;
    const m = ITEM_RE.exec(headingLine);
    if (!m?.[1] || !m[2]) return;
    const items = itemKeys(m[2]);
    if (!items) return;
    const keys = items.map((item) => (isTenQ && part ? `${part}.${item}` : item));
    const title = m[3] ?? '';
    const combinedLabel = keys.length > 1 ? `${m[1]} ${m[2]}` : undefined;
    const tooLong = headingLine.length > MAX_HEADING_CHARS;
    const fused = splitFusedHeading(title, form, keys, tooLong);
    if (fused) {
      const heading: Heading = {
        keys,
        rawTitle: fused.rawTitle,
        line: i,
        fusedParagraph: fused.paragraph,
        splitTitle: fused.splitTitle,
      };
      if (combinedLabel) heading.combinedLabel = combinedLabel;
      all.push(heading);
      return;
    }
    if (tooLong) return;
    if (looksLikeSentence(title) && !matchesKnownTitle(title, form, keys)) return;
    const heading: Heading = { keys, rawTitle: title, line: i };
    if (combinedLabel) heading.combinedLabel = combinedLabel;
    all.push(heading);
  });

  // Some annual-report renderers repeat a bare "Item 1A" as a running page
  // header. When the same key also has an explicit titled heading, three or
  // more bare occurrences are page furniture rather than section boundaries.
  const occurrenceKinds = new Map<string, { bare: number; titled: number }>();
  for (const heading of all) {
    const key = heading.keys.length === 1 ? heading.keys[0] : undefined;
    if (!key) continue;
    const counts = occurrenceKinds.get(key) ?? { bare: 0, titled: 0 };
    if (heading.rawTitle.trim()) counts.titled++;
    else counts.bare++;
    occurrenceKinds.set(key, counts);
  }
  const repeatedBareKeys = new Set(
    [...occurrenceKinds].filter(([, counts]) => counts.bare >= 3 && counts.titled > 0).map(([key]) => key),
  );
  const ignoredHeadingLines = new Set<number>();
  for (let i = all.length - 1; i >= 0; i--) {
    const heading = all[i];
    const key = heading?.keys.length === 1 ? heading.keys[0] : undefined;
    if (heading && key && !heading.rawTitle.trim() && repeatedBareKeys.has(key)) {
      ignoredHeadingLines.add(heading.line);
      all.splice(i, 1);
    }
  }

  if (all.length === 0) {
    warnings.push('No "Item N" headings were found; the document may not be a 10-K/10-Q or may be an exhibit.');
    return { sections: new Map(), warnings };
  }

  const documentEnd = crossReferenceIndexAt >= 0 ? crossReferenceIndexAt : lines.length;
  const bodyBetween = (h: Heading, end: number): string[] => {
    const body = h.fusedParagraph ? [h.fusedParagraph] : [];
    for (let lineNumber = h.line + 1; lineNumber < end; lineNumber++) {
      const line = lines[lineNumber];
      if (line && !ignoredHeadingLines.has(lineNumber) && !isNoise(line)) body.push(line);
    }
    return body;
  };
  const bodyOf = (i: number): { lines: string[]; chars: number } => {
    const h = all[i];
    const next = all[i + 1];
    if (!h) return { lines: [], chars: 0 };
    const body = bodyBetween(h, next ? next.line : documentEnd);
    return { lines: body, chars: body.reduce((n, l) => n + l.length, 0) };
  };
  const classifyAll = (): Classified[] => classify(all, (i) => {
    const body = bodyOf(i);
    const placeholder = body.lines.length === 1 && /^(?:none|not applicable|n\/a)\.?$/i.test(body.lines[0] ?? '');
    return { chars: body.chars, placeholder };
  });
  let classified = classifyAll();

  // Some filings repeat a full titled Item heading at the top of every page.
  // Merge only an exact key+title run with substantive text between every
  // occurrence; a different intervening heading makes the run ineligible.
  const titledGroups = new Map<string, { heading: Classified; index: number }[]>();
  classified.forEach((heading, index) => {
    const key = heading.keys.length === 1 ? heading.keys[0] : undefined;
    const title = heading.rawTitle.trim();
    if (!key || !title || heading.toc || heading.tocTail) return;
    const identity = `${key}\0${title}`;
    const group = titledGroups.get(identity) ?? [];
    group.push({ heading, index });
    titledGroups.set(identity, group);
  });
  const repeatedTitledLines = new Set<number>();
  const runningHeaderMerges = new Map<number, number>();
  for (const group of titledGroups.values()) {
    if (group.length < 3) continue;
    const separatedByRealBody = group.slice(1).every((entry, offset) => {
      const previous = group[offset];
      return previous !== undefined
        && entry.index === previous.index + 1
        && bodyOf(previous.index).chars >= MIN_BODY_CHARS;
    });
    if (!separatedByRealBody) continue;
    const first = group[0];
    if (!first) continue;
    runningHeaderMerges.set(first.heading.line, group.length - 1);
    for (const repeated of group.slice(1)) repeatedTitledLines.add(repeated.heading.line);
  }
  if (repeatedTitledLines.size > 0) {
    for (const line of repeatedTitledLines) ignoredHeadingLines.add(line);
    for (let i = all.length - 1; i >= 0; i--) {
      const heading = all[i];
      if (heading && repeatedTitledLines.has(heading.line)) all.splice(i, 1);
    }
    classified = classifyAll();
  }

  const kept = classified.map((c, i) => ({ c, i })).filter(({ c }) => !c.toc);
  if (kept.length === 0) {
    warnings.push(`Found ${all.length} Item headings but all of them sit in a table-of-contents cluster; no bodies to return.`);
    return { sections: new Map(), warnings };
  }

  // Candidate bodies run from each kept heading to the next *kept* heading.
  const candidates = new Map<string, { section: Section; bodyChars: number; tocTail: boolean; pageRef: boolean }[]>();
  kept.forEach(({ c: h }, idx) => {
    const next = kept[idx + 1]?.c;
    const end = next ? next.line : documentEnd;
    const body = bodyBetween(h, end);
    const paragraphs: Paragraph[] = body.map((text, index) => ({ index, text }));
    const charCount = body.reduce((n, l) => n + l.length, 0);
    for (const key of h.keys) {
      const title = titleFor(form, key, h.rawTitle);
      const section: Section = { item: key, title, paragraphs, charCount, warnings: [] };
      if (h.splitTitle) {
        section.warnings.push(`heading and first paragraph were in one block; split at ${h.splitTitle}`);
      }
      if (h.combinedLabel) {
        section.warnings.push(`Combined heading "${h.combinedLabel}": this body covers Items ${h.keys.join(', ')}`);
      }
      const mergedHeaders = runningHeaderMerges.get(h.line);
      if (mergedHeaders) section.warnings.push(`${mergedHeaders} repeated running headers merged`);
      const list = candidates.get(key) ?? [];
      list.push({ section, bodyChars: charCount, tocTail: h.tocTail, pageRef: hasPageRef(h.rawTitle) });
      candidates.set(key, list);
    }
  });

  const sections = new Map<string, Section>();
  for (const [key, list] of candidates) {
    // Prefer any candidate that is not a TOC tail; among those, the longest body.
    const pool = list.some((c) => !c.tocTail) ? list.filter((c) => !c.tocTail) : list;
    const best = pool.reduce((a, b) => (b.bodyChars > a.bodyChars ? b : a));
    if (best.bodyChars === 0) {
      warnings.push(`Item ${key}: heading found but no body text followed it; not returned.`);
      continue;
    }
    if (best.bodyChars < MIN_BODY_CHARS) {
      const preview = best.section.paragraphs[0]?.text.slice(0, 60) ?? '';
      best.section.warnings.push(`Item ${key}: body is only ${best.bodyChars} chars ("${preview}"); likely a placeholder such as "None." or "Not applicable."`);
    }
    const hasRealRival = list.some((candidate) =>
      candidate !== best && !candidate.tocTail && candidate.bodyChars >= MIN_BODY_CHARS && !candidate.pageRef,
    );
    if (hasRealRival) {
      best.section.warnings.push(`Item ${key} heading appeared ${list.length} times outside the table of contents; kept the longest body.`);
    }
    sections.set(key, best.section);
  }
  return { sections, warnings };
}

/**
 * Resolve a user-supplied item reference against parsed keys.
 * Accepts "1a", "Item 1A", "II.1A", "1A" for a 10-Q (if unambiguous).
 */
export function resolveItemKey(requested: string, available: string[]): { key: string } | { error: string } {
  const cleaned = requested.trim().toUpperCase().replace(/^ITEM\s+/, '').replace(/\s+/g, '');
  if (available.includes(cleaned)) return { key: cleaned };
  const suffixMatches = available.filter((k) => k.endsWith(`.${cleaned}`));
  if (suffixMatches.length === 1 && suffixMatches[0]) return { key: suffixMatches[0] };
  if (suffixMatches.length > 1) {
    return { error: `"${requested}" is ambiguous in this filing; specify one of: ${suffixMatches.join(', ')}` };
  }
  return { error: `Item "${requested}" was not found in this filing.` };
}
