import * as cheerio from 'cheerio';
import type { Section, Paragraph } from '../types.js';
import { titleFor } from './items.js';

/**
 * HTML → ordered lines of visible text.
 *
 * EDGAR filings are generated by a dozen different vendors; the only thing
 * they reliably share is that block-level elements delimit paragraphs.
 * We keep that structure and throw everything else away.
 */
export function htmlToLines(html: string): string[] {
  const $ = cheerio.load(html);
  $('script, style, noscript, head').remove();
  // Cells get a space so "Item 1A." + "Risk Factors" + "9" don't fuse into one token.
  $('td, th').each((_, el) => {
    $(el).append(' ');
  });
  // Force a line break after every block-level element.
  $('p, div, tr, li, h1, h2, h3, h4, h5, h6, table, section, article, blockquote, pre').each((_, el) => {
    $(el).append('\n');
  });
  $('br').replaceWith('\n');
  const raw = $('body').length ? $('body').text() : $.root().text();
  return raw
    .replace(/[​﻿­]/g, '') // zero-width space / BOM / soft hyphen — everywhere in EDGAR HTML
    .replace(/ /g, ' ')
    .split('\n')
    .map((l) => l.replace(/[ \t\r\f\v]+/g, ' ').trim())
    .filter((l) => l.length > 0);
}

const PART_RE = /^part\s+(i{1,3}|iv|[1-4])\s*[.:\-–—]?\s*(.*)$/i;
// "Item 1A." / "ITEM 7 —" / "Item 1A:" ... ; headings are short by construction.
const ITEM_RE = /^item\s+(\d{1,2}[a-c]?)\s*[.:\-–—]?\s*(.*)$/i;
const MAX_HEADING_CHARS = 140;
const MAX_TITLE_WORDS = 12;
/** Bodies shorter than this are returned only with a warning; TOC stubs never are. */
export const MIN_BODY_CHARS = 400;
/** ≥ this many headings within TOC_MAX_GAP lines of each other = a table of contents. */
const TOC_MIN_RUN = 3;
const TOC_MAX_GAP = 2;
// hasPageRef / classify below implement the cluster rule.

interface Heading {
  key: string;
  rawTitle: string;
  line: number;
}

const ROMAN: Record<string, string> = { '1': 'I', '2': 'II', '3': 'III', '4': 'IV' };

/** Lines that are page furniture rather than content. */
function isNoise(line: string): boolean {
  if (/^\d{1,3}$/.test(line)) return true; // page numbers
  if (/^table of contents$/i.test(line)) return true;
  if (/^(form\s+)?10-[kq]\b/i.test(line) && line.length < 40) return true;
  const part = PART_RE.exec(line);
  if (part && line.length < 60 && !looksLikeSentence(part[2] ?? '')) return true; // "PART II. OTHER INFORMATION"
  return false;
}

/**
 * "Item 7 of our revenue was…" and "Item 1A of Part I is incorporated…" are
 * sentences, not headings. A heading's title is short and starts with a capital.
 */
function looksLikeSentence(title: string): boolean {
  const t = title.trim();
  if (!t) return false;
  if (/^[a-z]/.test(t)) return true; // "of our revenue…"
  if (t.split(/\s+/).length > MAX_TITLE_WORDS) return true;
  return false;
}

/** TOC rows almost always end in a page reference: "Item 1A. Risk Factors 9". */
function hasPageRef(title: string): boolean {
  return /\s\d{1,4}$/.test(title) || /^\d{1,4}$/.test(title);
}

interface Classified extends Heading {
  bodyChars: number;
  /** Sits inside a table-of-contents cluster; never a section. */
  toc: boolean;
  /** Big body directly after a TOC cluster: either the first real heading or the last TOC row
   *  swallowing the preamble. Used only when no unflagged candidate exists. */
  tocTail: boolean;
}

/**
 * Classify headings. A run of ≥ TOC_MIN_RUN headings within TOC_MAX_GAP lines of
 * each other is a table of contents, whatever markup produced it. Members whose
 * title carries a page reference, or whose body is tiny, are dropped. A member
 * with a real body and no page reference ends the run and is flagged `tocTail`.
 */
function classify(headings: Heading[], bodyChars: (i: number) => number): Classified[] {
  const out: Classified[] = headings.map((h, i) => ({ ...h, bodyChars: bodyChars(i), toc: false, tocTail: false }));
  let runStart = 0;
  const closeRun = (endExclusive: number): void => {
    if (endExclusive - runStart < TOC_MIN_RUN) return;
    for (let k = runStart; k < endExclusive; k++) {
      const m = out[k];
      if (!m) continue;
      const stub = m.bodyChars < MIN_BODY_CHARS || hasPageRef(m.rawTitle);
      if (stub) m.toc = true;
      else m.tocTail = true; // only ever the final member — a stub would have continued the run
    }
  };
  for (let i = 1; i <= out.length; i++) {
    const prev = out[i - 1];
    const cur = out[i];
    const prevIsStub = prev !== undefined && (prev.bodyChars < MIN_BODY_CHARS || hasPageRef(prev.rawTitle));
    const contiguous = cur !== undefined && prev !== undefined && cur.line - prev.line <= TOC_MAX_GAP && prevIsStub;
    if (!contiguous) {
      closeRun(i);
      runStart = i;
    }
  }
  return out;
}

/**
 * Split a filing into Items.
 *
 * Every 10-K lists all Items twice — once in the table of contents, once as
 * real headings. Two defences, in order:
 *  1. drop clusters of headings that sit within a couple of lines of each other
 *     (that is a TOC, whatever markup it uses);
 *  2. if an Item still has several occurrences, keep the one with the largest body.
 * Short real bodies ("None.", "Not applicable.") are returned with a warning.
 */
export function splitItems(lines: string[], form: string): { sections: Map<string, Section>; warnings: string[] } {
  const warnings: string[] = [];
  const all: Heading[] = [];
  let part: string | null = null;
  const isTenQ = form.startsWith('10-Q');

  lines.forEach((line, i) => {
    if (line.length > MAX_HEADING_CHARS) return;
    const p = PART_RE.exec(line);
    if (p && p[1] && !looksLikeSentence(p[2] ?? '')) {
      const raw = p[1].toUpperCase();
      part = ROMAN[raw] ?? raw;
      return;
    }
    const m = ITEM_RE.exec(line);
    if (!m || !m[1]) return;
    const title = m[2] ?? '';
    if (looksLikeSentence(title)) return;
    const item = m[1].toUpperCase();
    const key = isTenQ && part ? `${part}.${item}` : item;
    all.push({ key, rawTitle: title, line: i });
  });

  if (all.length === 0) {
    warnings.push('No "Item N" headings were found; the document may not be a 10-K/10-Q or may be an exhibit.');
    return { sections: new Map(), warnings };
  }

  const bodyOf = (i: number): { lines: string[]; chars: number } => {
    const h = all[i];
    const next = all[i + 1];
    if (!h) return { lines: [], chars: 0 };
    const body = lines.slice(h.line + 1, next ? next.line : lines.length).filter((l) => !isNoise(l));
    return { lines: body, chars: body.reduce((n, l) => n + l.length, 0) };
  };
  const classified = classify(all, (i) => bodyOf(i).chars);
  const kept = classified.map((c, i) => ({ c, i })).filter(({ c }) => !c.toc);
  if (kept.length === 0) {
    warnings.push(`Found ${all.length} Item headings but all of them sit in a table-of-contents cluster; no bodies to return.`);
    return { sections: new Map(), warnings };
  }

  // Candidate bodies run from each kept heading to the next *kept* heading.
  const candidates = new Map<string, { section: Section; bodyChars: number; tocTail: boolean }[]>();
  kept.forEach(({ c: h }, idx) => {
    const next = kept[idx + 1]?.c;
    const end = next ? next.line : lines.length;
    const body = lines.slice(h.line + 1, end).filter((l) => !isNoise(l));
    const paragraphs: Paragraph[] = body.map((text, index) => ({ index, text }));
    const charCount = body.reduce((n, l) => n + l.length, 0);
    const section: Section = { item: h.key, title: titleFor(form, h.key, h.rawTitle), paragraphs, charCount, warnings: [] };
    const list = candidates.get(h.key) ?? [];
    list.push({ section, bodyChars: charCount, tocTail: h.tocTail });
    candidates.set(h.key, list);
  });

  const sections = new Map<string, Section>();
  for (const [key, list] of candidates) {
    // Prefer any candidate that is not a TOC tail; among those, the longest body.
    const pool = list.some((c) => !c.tocTail) ? list.filter((c) => !c.tocTail) : list;
    const best = pool.reduce((a, b) => (b.bodyChars > a.bodyChars ? b : a));
    if (best.bodyChars === 0) {
      warnings.push(`Item ${key}: heading found but no body text followed it; not returned.`);
      continue;
    }
    if (best.bodyChars < MIN_BODY_CHARS) {
      const preview = best.section.paragraphs[0]?.text.slice(0, 60) ?? '';
      best.section.warnings.push(`Item ${key}: body is only ${best.bodyChars} chars ("${preview}"); likely a placeholder such as "None." or "Not applicable."`);
    }
    if (list.length > 1) {
      best.section.warnings.push(`Item ${key} heading appeared ${list.length} times outside the table of contents; kept the longest body.`);
    }
    sections.set(key, best.section);
  }
  return { sections, warnings };
}

/**
 * Resolve a user-supplied item reference against parsed keys.
 * Accepts "1a", "Item 1A", "II.1A", "1A" for a 10-Q (if unambiguous).
 */
export function resolveItemKey(requested: string, available: string[]): { key: string } | { error: string } {
  const cleaned = requested.trim().toUpperCase().replace(/^ITEM\s+/, '').replace(/\s+/g, '');
  if (available.includes(cleaned)) return { key: cleaned };
  const suffixMatches = available.filter((k) => k.endsWith(`.${cleaned}`));
  if (suffixMatches.length === 1 && suffixMatches[0]) return { key: suffixMatches[0] };
  if (suffixMatches.length > 1) {
    return { error: `"${requested}" is ambiguous in this filing; specify one of: ${suffixMatches.join(', ')}` };
  }
  return { error: `Item "${requested}" was not found in this filing.` };
}
